config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  resources :notes
  
  authenticated :user do
      root 'notes#index', as: "authenticated_root"
end 
    
    
  root 'welcome#index'
  get '/subjects' => 'subjects#subjects'
  get '/posts' => 'posts#index'
end

app/models/note.rb
class Note < ActiveRecord::Base
    belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/nav_controller.rb
class NavController < ApplicationController
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
    before_action :find_note, only: [:show, :edit, :update, :destroy]
    def index
        @notes = Note.where(user_id: current_user)
    end
    
    def show
    end
    
    def new
        @note = current_user.notes.build
    end
    
    def create
        @note = current_user.notes.build(note_params)
        
        if @note.save
            redirect_to @note
        else
            render 'new'
        end
    end
    
    def edit
    end
    
    def update
        if @note.update(note_params)
            redirect_to @note
        else render 'edit'
            end
    end
    
    def destroy
        @note.destroy
        redirect_to notes_path
    end
    
    private
    
    def find_note
        @note = Note.find(params[:id])
    end
    
    def note_params
        params.require(:note).permit(:title, :content)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
	end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nav_helper.rb
module NavHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
<div class="container-custom">
<!-- Brand and toggle get grouped for better mobile display -->
<div class="navbar-header">
<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
<span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<a class="navbar-brand" href="#">School Help</a>
</div>

<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
<ul class="nav navbar-nav">
<% if user_signed_in? %>
  <li><a href="/subjects">Subjects <span class="sr-only">(current)</span></a></li>
<% else %>
  <li><a href="#features">Features <span class="sr-only">(current)</span> </a></li>
<% end %>

<% if user_signed_in? %>
  <li><a class="nav-link" href="/notes">My Notes <span class="sr-only">(current)</span></a></li>
<% else %>
  <li><a class="nav-link" href="#">Get Started <span class="sr-only">(current)</span></a></li>
<% end %>

<% if user_signed_in? %>
  <li><a class="nav-link" href="/posts">Forum<span class="sr-only">(current)</span></a></li>
<% else %>
  <li><a class="nav-link" href="#contact">Let's talk <span class="sr-only">(current)</span></a></li>
<% end %>
</ul>

<ul class="nav navbar-nav navbar-right">
 <% if user_signed_in? %>
<li><a href="#">Nicoloas Yorgos</a></li>
<li><%= link_to('Sign out', destroy_user_session_path, :method => :delete) %></li>
  <% else %>
  <li><%= link_to('Log in', new_user_session_path, :class => "sign-up-nav")%></li>
<li><%= link_to('Sign up', new_user_registration_path, :class => "sign-up-nav")%></li>
  <% end> %>
</ul>
</div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
  <head>
    <title>Online Notebook</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true  %>
    <%= favicon_link_tag "/images/favico.ico" %>
    <%= csrf_meta_tags  %>
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  </head>
  <body>
    <%= render 'layouts/nav' %>
    <%= yield  %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true  %>
    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js', 'data-turbolinks-track' => true  %>
  </body>
</html>

app/views/notes/_form.html.haml
= simple_form_for @note do |f|
  = f.input :title, placeholder: "Overskrift"
  = f.input :content, placeholder: "Indhold", class: "form-control"
  = f.button :submit, class: "button"

app/views/notes/_richform.html.erb
<%= semantic_form_for @post do |f| %>
  <%= f.inputs do %>
    <%= f.input :name %>
    <%= f.input :title %>
    <%= f.input :featured_image, :as => :rich_picker %>
    <%= f.input :body, :as => :rich, :config => { :default_style => "myCrazyPaperclipStyle" } %>
  <% end %>
  <%= f.buttons do %>
    <%= f.commit_button %>
  <% end %>
<% end %>

app/views/notes/edit.html.haml
%h1 Edit your note
.form-wrapper
  = render 'form'

= link_to "Cancel", note_path

app/views/notes/index.html.haml
.container-custom
  - if user_signed_in?
    .row
    - unless @notes.blank?
      - @notes.each do |note|
        %li.note.col-xs-6.col-md-3.bs-callout.bs-callout-danger
          %a.note-w{ href: (url_for [note])}
            .note-content
              %h2.note_title= note.title
              %p.note-date= time_ago_in_words(note.created_at) + " ago"

    - else
      %h2 Add a Note
      %p It appears you haven't created any notes yet.... You better create one now, bitch
      %button.btn.btn-success= link_to "New Note", new_note_path
  - else
    %h2 Sorry, bro, you're not allowed to be here until you've signed up

app/views/notes/new.html.haml
.page-header
  %h1.os.uc add a new Note
= render "form"

app/views/notes/show.html.haml
.page-header
  %h1.os.uc= @note.title
.os.m-b-20  
  %p.os.m-b-20= simple_format(@note.content)
= link_to "All notes", notes_path, class: "btn btn-success"
= link_to "Edit note", edit_note_path(@note), class: "btn btn-primary"
= link_to "Delete note", note_path(@note), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger"

app/views/posts/_postform.html.haml
= simple_form_for @post do |f|
	= f.input :title
	= f.input :content
	= f.submit :submit

app/views/posts/index.html.erb
<h1>Forum Baby?</h1>

<a href="/posts/new">Hej</a>

app/views/posts/new.html.erb
<h2>New Post</h2>

<% render 'postform' %>

app/views/subjects/subjects.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Untitled Project - Subjects</title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<% if signed_in? %>
  <!-- CONTENT GO HERE, MAN! -->
	<section class="subject-section container-custom">
		<h1>Subjects</h1>

		<div class="row" style="margin-left: 0px; margin-right: 0px; margin: 0 auto;">

  			<div class="col-md-3">
  				<div class="math-topic topic">
  					<div class="topic-icon">
              <%= image_tag("pi.svg", :height => '60px', :width => '60px') %>
  					</div>
  					<a class="topic-button">Matematik</a>
  				</div>
  			</div>

  			<div class="col-md-3">
  				<div class="science-topic topic">
  					<div class="topic-icon">
              <%= image_tag("science.svg", :height => '60px', :width => '60px') %>
  					</div>
  					<a class="topic-button">Kemi</a>
  				</div>
  			</div>

  			<div class="col-md-3">
  				<div class="fysik-topic topic">
  					<div class="topic-icon">
  						<%= image_tag("fysik.svg", :height => '60px', :width => '60px') %>
  					</div>
  					<a class="topic-button">Fysik</a>
  				</div>
  			</div>

  			<div class="col-md-3">
  				<div class="dansk-topic topic">
  					<div class="topic-icon">
  						<%= image_tag("grammar.svg", :height => '60px', :width => '60px') %>
  					</div>
  					<a class="topic-button">Dansk</a>
  				</div>
  			</div>


  			<div class="col-md-3">
  				<div class="english-topic topic">
  					<div class="topic-icon">
              <%= image_tag("english.svg", :height => '60px', :width => '60px') %>
  					</div>
  					<a class="topic-button">Engelsk</a>
  				</div>
  			</div>

  			<div class="col-md-3">
  				<div class="historie-topic topic">
  					<div class="topic-icon">
  						<%= image_tag("history.svg", :height => '60px', :width => '60px') %>
  					</div>
  					<a class="topic-button">Historie</a>
  				</div>
  			</div>

  			<div class="col-md-3">
  				<div class="biologi-topic topic">
  					<div class="topic-icon">
  						<%= image_tag("biologi.svg", :height => '60px', :width => '60px') %>
  					</div>
  					<a class="topic-button">Biologi</a>
  				</div>
  			</div>

  			<div class="col-md-3">
  				<div class="teknologi-topic topic">
  					<div class="topic-icon">
  						<%= image_tag("teknologi.svg", :height => '60px', :width => '60px') %>
  					</div>
  					<a class="topic-button">Teknologi</a>
  				</div>
  			</div>

		</div>


	</section>

  <%else%>
  <H2>Sut pik?</H2>
  <%end%>

	
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
</body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Untitled Project</title>
<!-- Stylesheets -->
</head>

<body>
<header>
<div class="container-custom">
<h1 class="index-header">Welcome to</h1>
<h2>the ultimate school helper site</h2>
</div>
<%= image_tag("browser1-01.svg", :alt => "browser-1", :class => 'browser-1') %>

</header>

<section id="features" class="feature-section">

<h1>features</h1>

<div class="feature-all">
<div class="feature-container container-custom">
<div class="feature-text-container-left-float">
<h2 class="feature-heading">Notebook</h2>
<p class="feature-text">Lorem ipsum dolor sit amet, ligula pede dui gravida aptent. Dui nibh id, iure quis amet eu phasellus, hendrerit tortor vel aliquam erat. Ut sit sed sed. Enim senectus, ultrices morbi massa massa.
</p>
</div>
<%= image_tag("texteditor.svg", :alt => "texteditor", :class => 'text-editor-svg svg') %>
<div style="clear: both;"></div>
</div>

<div class="feature-container container-custom">
<div class="feature-text-container-right-float">
<h2 class="feature-heading">Equations</h2>
<p class="feature-text">Lorem ipsum dolor sit amet, ligula pede dui gravida aptent. Dui nibh id, iure quis amet eu phasellus, hendrerit tortor vel aliquam erat. Ut sit sed sed. Enim senectus, ultrices morbi massa massa.
</p>
</div>
<%= image_tag("equations.svg", :alt => "equations", :class => 'equations-svg svg') %>
<div style="clear: both;"></div>
</div>

<div class="feature-container container-custom">
<div class="feature-text-container-left-float">
<h2 class="feature-heading">Calculators</h2>
<p class="feature-text">Lorem ipsum dolor sit amet, ligula pede dui gravida aptent. Dui nibh id, iure quis amet eu phasellus, hendrerit tortor vel aliquam erat. Ut sit sed sed. Enim senectus, ultrices morbi massa massa.
</p>
</div>
<%= image_tag("calculator-01.svg", :alt => "calculator", :class => 'calculator-svg svg') %>
<div style="clear: both;"></div>
</div>
</div>

<div class="margin"></div>
</section>

<section class="get-started-section">

</section>

</body>
</html>